### ISSUE TITLE
Action fails with unhelpful error message when PR branch is out of date with target branch

### ISSUE THREAD

**Issue by owenpearson** [ably/sdk-upload-action#19]
See [this run](https://github.com/ably/ably-flutter/runs/2785319804) for example behaviour.

**Comment by QuintinWillison** [comment]
We saw this again today and I think we've identified where the problem lies, and that is outside of the code in this repository.

It's surprising that the default behaviour of GitHub's [Checkout Action](https://github.com/actions/checkout) is that it creates a merge commit by default, rather than just running against `HEAD` of the branch underlying the pull request. Others have faced this issue too - see https://github.com/actions/checkout/issues/504

We see "Error: Conflict merging main into <SHA>":

<img width="631" alt="Screenshot 2021-07-05 at 10 25 05" src="https://user-images.githubusercontent.com/8318344/124449949-db9ac000-dd7b-11eb-8f53-4ba27c66e69f.png">

It looks like the workaround is documented in the checkout action's readme [here](https://github.com/actions/checkout#Checkout-pull-request-HEAD-commit-instead-of-merge-commit) (also mentioned in the issue I linked to above). Unfortunately that means we will need to update every workflow that we have, or at least definitely all of the ones that use our upload action, to explicitly checkout `head.sha`.

Remediation in respect of this repository specifically should be to update the readme to mention this, in order to save confusion in future.

**Comment by QuintinWillison** [comment]
We have been conforming the branch protection rule for the `main` branch in most of our open source repositories, specifically enabling "Require status checks to pass before merging" and its sub-option "Require branches to be up to date before merging".

As far as I can tell, that sub-option negates the need for our checkout action invocations to create a merge commit to run checks against, because we'll always be told "This branch is out-of-date with the base branch" with an "Update branch" button in the GitHub UI to add a merge commit from `main`, triggering checks to run again - thus `HEAD` of the pull request's underlying branch will always be adequate.

This brings me to the conclusion that we probably need to standardise the replacement of our existing checkout action invocations that currently look like this:

```yml
- uses: actions/checkout@v2
```

With this longer form:

```yml
- uses: actions/checkout@v2
  with:
    ref: ${{ github.event.pull_request.head.sha }}
```

This is very disappointing as it would have been really nice had we been able to use the checkout action without needing to specify any explict config (i.e. prefer convention over configuration). But, fundamentally, we're seeing too many occasions where we have multiple pull requests all targeting the `main` branch and some or all of them end up failing checks due to  workflow jobs that use this SDK Upload Action... because of this issue.

**Comment by owenpearson** [comment]
Just had another proper look in to this and I'm now thinking it's to do with this `auto_merge` option for creating a deployment. [From the docs](https://docs.github.com/en/rest/reference/repos#deployments):
> Attempts to automatically merge the default branch into the requested ref, if it's behind the default branch.
> Default: `true`

I'll make a 1.1 release tomorrow with this set to false.

**Comment by QuintinWillison** [comment]
Ooh, exciting. Thanks for looking, @owenpearson. Fingers crossed! 😄
